import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // standalone bundles only the files Next.js actually needs into .next/standalone,
  // which is what packages/web/Dockerfile copies into the runtime image.
  output: "standalone",
  outputFileTracingRoot: path.join(__dirname, "../.."),
  images: {
    remotePatterns: [{ protocol: "https", hostname: "**" }, { protocol: "http", hostname: "**" }],
  },
  // Legacy favicon and apple-touch-icon URLs that browsers / RSS readers /
  // social-share scrapers (FB, Slack, X, iOS Safari) probe regardless of
  // <link rel=icon>. Without these the requests hit the catch-all 404
  // handler — minor quality signal, log noise, occasional broken
  // social-card icons. Permanent redirects to the modern Next-generated
  // assets that already 200.
  async headers() {
    return [
      {
        // Static-y discovery files served from packages/web/public/. They
        // change once per deploy; Next ships them with max-age=0 by default
        // which means Cloudflare can never cache, and every AI/RSS/social
        // crawler hits origin. 1-hour public cache + 24h SWR drops the
        // origin pressure dramatically; if we deploy a change to one of
        // these the next deploy invalidates the CDN cache anyway.
        source: "/:file(robots.txt|llms.txt|81b0a3ff408a96ef5c0381a78aae7f58.txt)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400" },
        ],
      },
      {
        // /.well-known/agents.json + security.txt — same rationale.
        source: "/.well-known/:file(agents.json|security.txt)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400" },
        ],
      },
      {
        // /manifest.webmanifest is generated by Next from app/manifest.ts and
        // ships with the dynamic-route default `max-age=0, must-revalidate`.
        // Browsers re-fetch it on install + on visibility changes; Lighthouse
        // PWA audits also re-fetch each run. It only changes once per deploy.
        source: "/manifest.webmanifest",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400" },
        ],
      },
      {
        // /sitemap.xml ships with Next's default `max-age=0, must-revalidate`
        // because it's a dynamic route. That means Cloudflare cannot cache
        // it — every Googlebot/Bingbot/IndexNow hit reaches origin and
        // triggers a full render of all ~14k URLs. The module-level harvest
        // cache in sitemap.ts already keeps the render fast, but origin
        // still pays the work. A short edge TTL is safe: catalog changes
        // every few minutes, and sitemap lastmod values are advisory.
        source: "/sitemap.xml",
        headers: [
          { key: "Cache-Control", value: "public, max-age=300, s-maxage=300, stale-while-revalidate=1800" },
        ],
      },
      {
        // /s/{id} agent-snapshot pages are token-addressed (the unguessable id
        // is the credential, see api/middleware/auth.ts) and immutable until
        // the underlying snapshot expires 24h after creation. Next's dynamic-
        // route default ships 'private, no-cache, no-store' so every viewer
        // hit origin even though many recipients typically share one URL
        // (audit-trail / proof-of-what-the-agent-saw flows). Match the API
        // /v1/snapshots/{id} cache policy (commit 480c816) so the WEB page
        // wrapping the same data is just as cacheable.
        source: "/s/:id",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400, immutable" },
        ],
      },
    ];
  },
  async redirects() {
    return [
      { source: "/favicon.ico", destination: "/icon.svg", permanent: true },
      { source: "/apple-touch-icon.png", destination: "/apple-icon", permanent: true },
      { source: "/apple-touch-icon-precomposed.png", destination: "/apple-icon", permanent: true },
      // PWA manifest legacy paths. Next 15 emits its manifest at the
      // modern .webmanifest extension; PWA installers and some crawlers
      // (Lighthouse, Edge "Install app") still probe the older paths.
      { source: "/manifest.json", destination: "/manifest.webmanifest", permanent: true },
      { source: "/site.webmanifest", destination: "/manifest.webmanifest", permanent: true },
      // Legacy security.txt path. RFC 9116 defines /.well-known/security.txt
      // as the canonical location, but plenty of scanners and operators
      // still probe the bare /security.txt path.
      { source: "/security.txt", destination: "/.well-known/security.txt", permanent: true },
      // Legacy sitemap-index variants. Some older crawlers probe these
      // names instead of /sitemap.xml. We don't actually emit a sitemap
      // INDEX (one file with <14k URLs covers everything well under the
      // spec's 50k-per-file limit), but the canonical sitemap is what
      // they want either way.
      { source: "/sitemap_index.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/sitemap-index.xml", destination: "/sitemap.xml", permanent: true },
      // Legacy index file probes. Apache/nginx classic-CMS conventions
      // expose /index.html for the homepage; some directory listings,
      // copy-paste docs, and a few crawler implementations still hit
      // these. 404 is a quality-signal hit; redirect to canonical home.
      { source: "/index.html", destination: "/", permanent: true },
      { source: "/index", destination: "/", permanent: true },
      { source: "/index.htm", destination: "/", permanent: true },
      { source: "/home", destination: "/", permanent: true },
      // NOTE: previously had Title-case → lowercase redirects here for
      // /Search, /Product/:id, /About, /Seller. They caused an infinite
      // redirect loop in production: Next.js's `redirects()` path matcher
      // is CASE-INSENSITIVE by default, so `/Product/:id` ALSO matched
      // `/product/<uuid>` (the canonical lowercase form) and 308'd it to
      // itself. Every product page broke for ~30 minutes after deploy.
      // Reverted; uppercase variants will 404 (which Google handles fine
      // — it's a far better failure mode than infinite redirect loops).
      // A correct case-redirect implementation needs middleware that
      // checks `request.nextUrl.pathname !== request.nextUrl.pathname.toLowerCase()`.
    ];
  },
};

export default nextConfig;
